on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    name: Initial for release
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Get version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Make release
      uses: marvinpinto/action-automatic-releases@latest
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          LICENSE
          public/*
